version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=Emmanuel_7
      - MYSQL_DATABASE=db_allinone
      - MYSQL_USER=allinone
      - MYSQL_PASSWORD=Emmanuel_7
  back:
    build:
      context: ./back-allinone
      dockerfile: Dockerfile
    depends_on:
      - mysql   
    ports:
      - "5000:5000"
    restart: always
    environment:
    - SQLALCHEMY_DATABASE_URI=mysql+pymysql://allinone:Emmanuel_7@localhost/db_allinone
    - SQLALCHEMY_TRACK_MODIFICATIONS=false
    - SECRET_KEY=OPEN
    networks:
      - app_network

  
  front:
    build:
      context: ./front-allinone
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network
  #nginx:
   # image: nginx:stable-alpine
    #volumes:
     # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #depends_on:
     # - back
      #- front
    #networks:
     # - app_network
  #nginx-proxy:
   # image: nginx:alpine
    #volumes:
     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #ports:
     # - "443:443"
   # depends_on:
    #  - back
    #  - front

volumes:
  db-data: {}

networks:
  app_network:
    driver: bridge